# Site settings
title: One Shared Truth Conference 1STC
email: 
description: 1STC at Fordham Universityâ€™s Gabelli School of Business brings together leaders from finance, technology, and academia to examine how innovation is reshaping global markets. # > this means to ignore newlines until "baseurl:"
baseurl: "/1STC" # the subpath of your site, e.g. /blog/
url: "https://fordhamblockchain.github.io" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
